name: Instagram Scheduler - ink_wisps

on:
  schedule:
    - 
jobs:
  ink-wisps:
    concurrency:
      group: ink_wisps
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      IG_INK_WISPS_TOKEN: ${{ secrets.IG_INK_WISPS_TOKEN }}
      IG_INK_WISPS_ID: ${{ secrets.IG_INK_WISPS_ID }}
      DROPBOX_INK_WISPS_REFRESH: ${{ secrets.DROPBOX_INK_WISPS_REFRESH }}
      DROPBOX_INK_WISPS_APP_KEY: ${{ secrets.DROPBOX_INK_WISPS_APP_KEY }}
      DROPBOX_INK_WISPS_APP_SECRET: ${{ secrets.DROPBOX_INK_WISPS_APP_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install dropbox requests python-telegram-bot==13.15 pytz pynacl

      - name: Print current UTC time
        run: date -u

      - name: Run Script
        run: python ink_wisps_post.py
